spring.application.name=api
spring.datasource.url=jdbc:postgresql://ep-polished-mud-atl9xull-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2URkidHM1OQG

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.main.allow-circular-references=true

# Razorpay Configuration
razorpay.key.id=rzp_test_dummy_key_id
razorpay.key.secret=dummy_key_secret